### ISSUE TITLE
Is there a way to go back to the previous dialog boxes?

### ISSUE THREAD

**Issue by alevelasco9** [allanvalk/fancydialogue#1]
Is there a way to go back to the previous dialog boxes?
When I define the action of "fancyDialogue_test_1" in the dialog box "fancyDialogue_test_2" it tells me that "fancyDialogue_test_1" is not defined.

**Comment by allanvalk** [comment]
Currently no, there is no way to get back in dialogue, cause I haven't thought about it, but might add as an optional thing.
For the second one, dialogues must be placed in reverse order in the _dialogues.sqf_ as it's in the example template. I've tried to remove this dependecy on the placement, but arma reads everything in order and wants dialogue to be defined before sees its request somewhere later.

**Comment by funnycookieever** [comment]
Currently no, there is no way to get back in the dialogue, cause I haven't thought about it.
This error show up because arma wants to already have a defined dialogue when it reads through the code there it's requested.

**Comment by alevelasco9** [comment]
Is possible that you can use one array with the lists definited? wolud be how leave definite the variable and use another options into the array.

I can't help you too mucho because I don't know scripting.

Sorry for my english but i dont know so much.

**Comment by funnycookieever** [comment]
Added the functionality, now you can get back to any dialogue, just need to define boolean in the `dialogue.sqf`.
